# Before you start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import numpy as np
import pandas as pd
import scipy.stats
import sys

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents. 

In [2]:
# Your code here:
salaries = pd.read_csv('Current_Employee_Names__Salaries__and_Position_Titles.csv')
salaries.shape

(33702, 8)

Examine the `salaries` dataset using the `head` function below.

In [3]:
# Your code here:
salaries.head(10)

Name                               Job Titles  \
0   ADRIANO,  RACQUEL ANNE                                PARAMEDIC   
1        AFFANEH,  MAHIR A                           POLICE OFFICER   
2        AFOENYI,  PHYLLIS                TITLE V PROGRAM TRAINEE I   
3          AGAR,  BULENT B                      DEPUTY COMMISSIONER   
4          AGEE,  LAWRENCE                           POLICE OFFICER   
5        AGNEW,  ANTONIO E                       MOTOR TRUCK DRIVER   
6        AGNEW,  MELISSA M                                 SERGEANT   
7        AGOSTA,  JOSEPH J   POLICE OFFICER (ASSIGNED AS DETECTIVE)   
8  AGOSTINELLI,  MICHAEL A  FIREFIGHTER (PER ARBITRATORS AWARD)-EMT   
9        AGOSTINI,  LUIS R                                 ASST DIR   

         Department Full or Part-Time Salary or Hourly  Typical Hours  \
0              FIRE                 F           Salary            NaN   
1            POLICE                 F           Salary            NaN   
2  FAMILY & SUPPORT                 P           Hourly           20.0   
3       WATER MGMNT                 F           Salary            NaN   
4            POLICE                 F           Salary            NaN   
5          AVIATION                 F           Hourly           40.0   
6            POLICE                 F           Salary            NaN   
7            POLICE                 F           Salary            NaN   
8              FIRE                 F           Salary            NaN   
9            POLICE                 F           Salary            NaN   

   Annual Salary  Hourly Rate  
0        72510.0          NaN  
1        93354.0          NaN  
2            NaN        13.00  
3       132972.0          NaN  
4        90024.0          NaN  
5            NaN        37.45  
6       111444.0          NaN  
7       103932.0          NaN  
8       107106.0          NaN  
9        95736.0          NaN

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [4]:
# Your code here:
salaries.isna().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        25528
Annual Salary         8174
Hourly Rate          25528
dtype: int64

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [5]:
# Your code here:
salaries.groupby(['Salary or Hourly']).agg({'Name':'count'})

Name
Salary or Hourly       
Hourly             8174
Salary            25528

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [6]:
# Your code here:
salaries.groupby('Department').agg({'Name':'count'})

Name
Department                
ADMIN HEARNG            38
ANIMAL CONTRL           75
AVIATION              1856
BOARD OF ELECTION      111
BOARD OF ETHICS          8
BUDGET & MGMT           44
BUILDINGS              258
BUSINESS AFFAIRS       167
CITY CLERK              88
CITY COUNCIL           362
COPA                   123
CULTURAL AFFAIRS        74
DAIS                  1033
DISABILITIES            28
FAMILY & SUPPORT       656
FINANCE                544
FIRE                  4627
HEALTH                 467
HOUSING                 66
HOUSING & ECON DEV     154
HUMAN RELATIONS         17
HUMAN RESOURCES         75
INSPECTOR GEN           95
LAW                    398
LICENSE APPL COMM        1
MAYOR'S OFFICE         104
OEMC                  1737
POLICE               13848
POLICE BOARD             2
PROCUREMENT             84
PUBLIC LIBRARY        1088
PUBLIC SAFETY ADMIN    244
STREETS & SAN         2175
TRANSPORTN            1113
TREASURER               28
WATER MGMNT           1914

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [7]:
#np.set_printoptions(threshold=sys.maxsize)
hr_sample = salaries["Hourly Rate"].to_numpy()
hr_sample = hr_sample[~np.isnan(hr_sample)] #removes nulls
hr_sample

array([13.  , 37.45, 40.78, ..., 51.43, 49.35, 37.45])

In [8]:
# Two-sided test:
# Null hypothesis or H0: mean hourly wage value = 30
# Alternative hyp or H1: mean hourly wage <> 30

In [9]:
# Your code here:
from scipy.stats import ttest_1samp

stat, pval = ttest_1samp(hr_sample, 30)
print('stat is  ', stat)
print('pvalue for the two-tailed test is ', pval)

#True value of sample mean is higher by 31 x SEM

stat is   31.211500329216044
pvalue for the two-tailed test is  3.825475847673794e-202


We reject hypothesis as p value is less than alpha 0.05. This is a two-sided test so we don't need to look at stat

In [10]:
#sample mean - hypothesized mean
np.mean(hr_sample) - 30

4.586449718620017

In [11]:
#sem x stat
scipy.stats.sem(hr_sample)*stat

4.586449718620017

In [12]:
#sample mean
print(np.mean(hr_sample))

34.58644971862002


We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

In [13]:
policedf = salaries[salaries["Department"]=='POLICE']

p_sample = policedf["Annual Salary"].to_numpy()
p_sample = p_sample[~np.isnan(p_sample)]
p_sample

array([ 93354.,  90024., 111444., ...,  76266.,  90024.,  93354.])

In [14]:
# One-sided test:
# Null hypothesis or H0: mean annualy salary value this year <= 86000 last year
# Alternative hyp or H1: mean annualy salary value this year > 86000 last year

#true if pvalue is less than 0.05 and stat has to point in correct direction(H0)

In [15]:
stat, pval = ttest_1samp(p_sample, 86000)

print('stat is  ', stat)
print('pvalue for the one-tailed test is ', pval/2)

stat is   18.51748561981861
pvalue for the one-tailed test is  6.119566952121482e-76


In [16]:
# stat is 18.51748561981861 - True value of sample mean is higher by 18 x SEM

print(scipy.stats.sem(p_sample)*stat)
print(np.mean(p_sample))

2834.118923611109
88834.11892361111


Here, we also reject the null hypothesis because pvalue is less then 0.05 and stat is pointing in the wrong direction to the null hypothesis.

Using the `crosstab` function, find the department that has the most hourly workers. 

In [17]:
# Your code here:
pd.crosstab(salaries['Department'], salaries['Salary or Hourly']).sort_values(by = 'Hourly', ascending=False).head()

Salary or Hourly  Hourly  Salary
Department                      
STREETS & SAN       1846     329
WATER MGMNT         1558     356
AVIATION            1214     642
OEMC                1077     660
DAIS                 745     288

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

In [18]:
dept = salaries[salaries['Department']=='STREETS & SAN']
hourly_workers = dept[dept['Salary or Hourly'] == 'Hourly']

In [19]:
hw_sample = hourly_workers["Hourly Rate"].to_numpy()
hw_sample = hw_sample.astype(float)
hw_sample

array([40.78, 38.52, 38.52, ..., 37.45, 38.52, 25.95])

In [20]:
# One-sided test:
# Null hypothesis or H0: mean hourly wage >= 35
# Alternative hyp or H1: mean hourly wage < 35

stat, pval = ttest_1samp(hw_sample, 35)

print('stat is  ', stat)
print('pvalue for the one-tailed test is ', pval/2)

stat is   4.000138803968834
pvalue for the one-tailed test is  3.2902372218867895e-05


In [21]:
np.mean(hw_sample)

35.5522968580715

Here although the pvalue is lower than alpha, we DO NOT reject the null hypothesis because stat is pointing in the direction of the null hypothesis

# Challenge 3: To practice - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [22]:
# use data from earlier
# sample mean
np.mean(hr_sample)

34.58644971862002

In [23]:
# Your code here:
confidence_level = 0.95
degrees_freedom = len(hr_sample) - 1
sample_mean = np.mean(hr_sample)
sample_standard_error = scipy.stats.sem(hr_sample)

confidence_interval = scipy.stats.t.interval(confidence_level, 
                                             degrees_freedom, 
                                             sample_mean, 
                                             sample_standard_error)

In [24]:
print( 'confidence interval is ', confidence_interval, '.' )

confidence interval is  (34.29839539204317, 34.874504045196865) .


Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [25]:
# use data from earlier
# sample mean
np.mean(p_sample)

88834.11892361111

In [26]:
# Your code here:
confidence_level = 0.95
degrees_freedom = len(p_sample) - 1
sample_mean = np.mean(p_sample)
sample_standard_error = scipy.stats.sem(p_sample)

confidence_interval = scipy.stats.t.interval(confidence_level, 
                                             degrees_freedom, 
                                             sample_mean, 
                                             sample_standard_error)

In [27]:
print( 'confidence interval is ', confidence_interval, '.' )

confidence interval is  (88534.1182885883, 89134.11955863392) .


# Bonus Challenge - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [28]:
salaries.groupby(['Salary or Hourly']).agg({'Name':'count'})

Name
Salary or Hourly       
Hourly             8174
Salary            25528

In [30]:
# P: Observed sample proportion , NOBS
# Po: Hypothesized Population Proportion, VALUE
# n: Sample size, COUNT

#H0: number of hourly workers = 25%
#H1: number of hourly workers <> 25%
#Significance Level: 0.05

In [31]:
# Your code here:
from statsmodels.stats.proportion import proportions_ztest
  
# perform one proportion z-test
proportions_ztest(count=8174, nobs=33702, value=0.25)

(-3.1962453870335, 0.0013922864704323116)

Here we reject the null hypothesis because stat is negative meaning number of hourly workers is less than 25%, also p value is less than alpha. 